[package]
name = "teaclient"
version = "0.1.0"
description = "A OpenSourced Client That looks nice.."
authors = ["you"]
license = "EPL-2.0"
repository = "https://github.com/teaclientmc/launcher"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
serde_json = "*"
serde = "1.0.194"
tauri = { version = "*", features = [ "macos-private-api", "api-all"] }
tokio = { version = "*", features = ["full"] }
minecraft-essentials = {git = "https://github.com/minecraft-essentials/minecraft-essentials"}
dotenv = "0.15.0"
keyring = "2.3.1"


[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
