[package]
name = "teaclient"
version = "0.1.0"
description = "A OpenSourced Client That looks nice.."
authors = ["you"]
license = "EPL-2.0"
repository = "https://github.com/teaclientmc/launcher"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "cdylib", "rlib", "lib"]

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
serde_json = "*"
serde = "1.0.194"
tauri = { version = "2.0.0-beta", features = [ "macos-private-api"] }
tokio = { version = "*", features = ["full"] }
minecraft-essentials = {git = "https://github.com/minecraft-essentials/minecraft-essentials"}
dotenv = "0.15.0"
keyring = "2.3.1"
tauri-plugin-process = "2.0.0-beta.1"
tauri-plugin-clipboard-manager = "2.0.0-beta.1"
tauri-plugin-fs = "2.0.0-beta.1"
tauri-plugin-shell = "2.0.0-beta.1"
tauri-plugin-dialog = "2.0.0-beta.1"
tauri-plugin-http = "2.0.0-beta.1"
tauri-plugin-os = "2.0.0-beta.1"
tauri-plugin-notification = "2.0.0-beta.1"


[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-global-shortcut = "2.0.0-beta.1"
