[package]
name = "teaclient"
version = "0.2.0"
description = "A OpenSourced Client That looks nice.."
authors = ["TeaClient Maintainers"]
license = "EPL-2.0"
repository = "https://github.com/teaclientmc/launcher"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = [ "macos-private-api"] }
tauri-plugin-clipboard-manager = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-store = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-http = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }

serde_json = "*"
serde = "*"
tokio = { version = "*", features = ["macros"] }
minecraft-essentials = { git = "https://github.com/minecraft-essentials/minecraft-essentials", branch = "eveeifyeve/minecraft-auth"}

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-global-shortcut = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
