name: Publish TeaClient
on: 
    push:
        branches: ["main"]
jobs: 
    publish-tauri:
        permissions:
          contents: write
        strategy:
          fail-fast: false
          matrix:
            settings:
              - platform: 'macos-latest' # for Arm based macs (M1 and above).
                args: '--target aarch64-apple-darwin'
              - platform: 'macos-latest' # for Intel based macs.
                args: '--target x86_64-apple-darwin'
              - platform: 'ubuntu-22.04' 
                args: ''
              - platform: 'windows-latest'
                args: ''
        runs-on: ${{ matrix.settings.platform }}
        steps:
          - uses: actions/checkout@v2
          - uses: oven-sh/setup-bun@v1
            with: 
                bun-version: latest

          - uses: dtolnay/rust-toolchain@stable
            with:
                targets: ${{ matrix.settings.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
          - if: matrix.settings.platform == 'ubuntu-22.04' # This must match the platform value defined above.
            run: |
                sudo apt-get update
                sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

          - name: install frontend dependencies
            run: bun install

          - uses: tauri-apps/tauri-action@v0
            env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
             tagName: v__VERSION__
             releaseName: 'App v__VERSION__'
             releaseBody: | 
              A new version of teaclient has been released
             args: ${{ matrix.settings.args }}